### ISSUE TITLE
error: use of undeclared identifier 'NSEventMaskKeyDown'

### ISSUE THREAD

**Issue by ryandesign** [kovidgoyal/kitty#2700]
**Describe the bug**
[kitty fails to build on OS X 10.11](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/114925/steps/install-port/logs/stdio). The first error is:

```
/usr/bin/clang -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=17 -DGL_SILENCE_DEPRECATION -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -Wall -Wstrict-prototypes -std=c99 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidden -D_FORTIFY_SOURCE=2 -arch x86_64 -isysroot/ -flto -pthread -I/opt/local/include/libpng16 -I/opt/local/include/harfbuzz -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c kitty/mouse.c -o build/fast_data_types-mouse.c.oglfw/cocoa_init.m:649:55: error: use of undeclared identifier 'NSEventMaskKeyDown'; did you mean 'kEventRawKeyDown'?
        [NSEvent addLocalMonitorForEventsMatchingMask:NSEventMaskKeyDown
                                                      ^~~~~~~~~~~~~~~~~~
                                                      kEventRawKeyDown
/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/CarbonEvents.h:4550:3: note: 'kEventRawKeyDown' declared here
  kEventRawKeyDown              = 1
  ^
```

**To Reproduce**
1. Build kitty on OS X 10.11

**Expected behavior**
Successful build

**Enviroment details**
OS: OS X El Capitan v10.11.6 (15G22010)
Xcode v8.2.1 (8C1002)

**Additional context**
[NSEventMaskKeyDown](https://developer.apple.com/documentation/appkit/nseventmask/nseventmaskkeydown) was introduced in the macOS 10.12 SDK.

I didn't know if it was intentional that kitty requires 10.12 or later. I didn't see a minimum OS version mentioned in the read me or on the main web site or the FAQ on the web site.

**Comment by kovidgoyal** [comment]
kitty does not support macOS 10.11 I'm afraid. If you search a bit in th
eissues you will find patches from other people that get it to mostly
work.

**Comment by ryandesign** [comment]
> kitty does not support macOS 10.11 I'm afraid.

That's fine. Perhaps you could add that information to the readme, web site and/or FAQ so that other users can find it more easily?
