### ISSUE TITLE
Fails to build with wayland-protocols 1.32 due to -Werror

### ISSUE THREAD

**Issue by jbeich** [kovidgoyal/kitty#6422]
**Describe the bug**
Regressed by [wayland-protocols@c124b641b346](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/commit/c124b641b346). From [error log](https://github.com/kovidgoyal/kitty/files/11953724/kitty-0.28.1.log):
```c
glfw/wl_window.c:528:17: error: enumeration value 'XDG_TOPLEVEL_STATE_SUSPENDED' not handled in switch [-Werror,-Wswitch]
        switch (*state) {
                ^
```
Upstream glfw is not affected due to not using `-Werror` by default.

Workaround: Pass `--ignore-compiler-warnings` to disable `-Werror`.

**To Reproduce**
1. Upgrade wayland-protocols to 1.32
2. Build as `linux-package`

**Comment by kovidgoyal** [comment]
fixed

**Comment by jbeich** [comment]
Still fails with the same error unless I apply the following:
```
--- a/glfw/wl_window.c	v0.28.1 + 95d15648fa37
+++ b/glfw/wl_window.c
@@ -529,7 +529,7 @@ xdgToplevelHandleConfigure(void* data,
             C(TOPLEVEL_STATE_TILED_RIGHT);
             C(TOPLEVEL_STATE_TILED_TOP);
             C(TOPLEVEL_STATE_TILED_BOTTOM);
-#ifdef XDG_TOPLEVEL_STATE_TILED_SUSPENDED_SINCE_VERSION
+#ifdef XDG_TOPLEVEL_STATE_SUSPENDED_SINCE_VERSION
             C(TOPLEVEL_STATE_SUSPENDED);
 #endif
 #undef C
```
