### ISSUE TITLE
error: use of undeclared identifier 'NSControlStateValueOn'

### ISSUE THREAD

**Issue by judaew** [kovidgoyal/kitty#3531]
**Describe the bug**

[kitty fails to build on macOS 10.12](https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/144845/steps/install-port/logs/stdio):

```
glfw/cocoa_window.m:1537:28: error: use of undeclared identifier 'NSControlStateValueOn'
              item.state = NSControlStateValueOn;
                           ^
glfw/cocoa_window.m:1539:28: error: use of undeclared identifier 'NSControlStateValueMixed'
              item.state = NSControlStateValueMixed;
                           ^
glfw/cocoa_window.m:1542:47: error: use of undeclared identifier 'NSControlStateValueOn'
          item.state = controller.isDesired ? NSControlStateValueOn : NSControlStateValueOff;
                                              ^
glfw/cocoa_window.m:1542:71: error: use of undeclared identifier 'NSControlStateValueOff'
          item.state = controller.isDesired ? NSControlStateValueOn : NSControlStateValueOff;
                                                                      ^
4 errors generated.
```

**To Reproduce**
1. Build kitty on macOS 10.12

**Expected behavior**
Successful build

**Environment details**
OS: macOS 10.12
Xcode 9.2

**Additional context**

[NSControlStateValue](https://developer.apple.com/documentation/appkit/nscontrolstatevalue?language=objc) was introduced in the macOS 10.13 SDK. I could not find the minimum required OS version on the website or FAQ. Am I correct in understanding kitty requires 10.13 or later to build?

**Comment by kovidgoyal** [comment]
this is already fixed in master
