### ISSUE TITLE
Build fails on OS X El Capitan (10.11.6) - os/log.h file not found

### ISSUE THREAD

**Issue by metayan** [kovidgoyal/kitty#555]
All mentioned dependencies are installed, but this happens:
```
make app
python3 setup.py kitty.app
CC: clang (4, 2)
Compiling kitty/logging.c ...
clang -MMD -D_XOPEN_SOURCE=700 -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=9 -Wextra -Wno-missing-field-initializers -Wall -std=c99 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidden -flto -pthread -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/harfbuzz/1.7.6_2/include/harfbuzz -I/usr/local/Cellar/glib/2.56.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/graphite2/1.3.10/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c /src/kitty/kitty/logging.c -o /src/kitty/build/fast_data_types-logging.c.o
/src/kitty/kitty/logging.c:14:10: fatal error: 'os/log.h' file not found
#include <os/log.h>
         ^
1 error generated.
make: *** [Makefile:34: app] Error 1
```

There is no `log.h` in `/usr/include/os` on this system:
```
ll /usr/include/os/
total 8
-rw-r--r-- 1 root wheel  9753 2016-02-27 07:01:41 activity.h
-r--r--r-- 1 root wheel  4232 2015-12-13 01:38:35 base.h
-rw-r--r-- 1 root wheel  5212 2016-02-10 02:10:30 object.h
-rw-r--r-- 1 root wheel 26808 2016-02-27 07:01:41 trace.h
```

However, the installed Command Line Tools have it:
```
ll /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/os/
total 24
-rw-r--r-- 1 root wheel 19141 2016-11-19 03:38:28 activity.h
-rw-r--r-- 1 root wheel  2722 2016-10-21 23:08:05 availability.h
-rw-r--r-- 1 root wheel  7167 2016-08-09 02:45:35 base.h
-rw-r--r-- 1 root wheel  4382 2016-08-09 02:45:35 lock.h
-rw-r--r-- 1 root wheel 17352 2016-11-19 03:38:28 log.h
-rw-r--r-- 1 root wheel  8490 2016-09-26 23:53:58 object.h
-r--r--r-- 1 root wheel  5386 2016-11-18 05:22:39 overflow.h
-rw-r--r-- 1 root wheel 17930 2016-11-19 03:38:28 trace.h
```

So tried
```
cd /usr/local/include
ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/os .
```
but that resulted in
```
make app
python3 setup.py kitty.app
CC: clang (4, 2)
Compiling kitty/logging.c ...
clang -MMD -D_XOPEN_SOURCE=700 -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=9 -Wextra -Wno-missing-field-initializers -Wall -std=c99 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidde
n -flto -pthread -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/harfbuzz/1.7.6_2/include/harfbuzz -I/usr/local/Cellar/glib/2.56.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.1/lib/glib-2.0/include -I/usr/local/opt
/gettext/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/graphite2/1.3.10/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/usr/local/Cellar/python/3.6.5/Frameworks/Pyt
hon.framework/Versions/3.6/include/python3.6m -c /src/kitty/kitty/logging.c -o /src/kitty/build/fast_data_types-logging.c.o
In file included from /src/kitty/kitty/logging.c:14:
In file included from /usr/local/include/os/log.h:29:
/usr/local/include/os/trace.h:302:24: error: expected parameter declarator
__API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0))
                       ^
/usr/local/include/os/trace.h:302:24: error: expected ')'
/usr/local/include/os/trace.h:302:23: note: to match this '('
__API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0))
                      ^
```
instead.

Replacing `__APPLE__` by `__MAC_10_12` in `logging.c` works as a fix for El Capitan, and might work on macOS 10.12 and higher:
```diff
diff --git a/kitty/logging.c b/kitty/logging.c
index 45c8817..db0296e 100644
--- a/kitty/logging.c
+++ b/kitty/logging.c
@@ -10,7 +10,7 @@
 #include <stdarg.h>
 #include <time.h>
 #include <sys/time.h>
-#ifdef __APPLE__
+#ifdef __MAC_10_12
 #include <os/log.h>
 #endif
 
@@ -21,7 +21,7 @@ void
 log_error(const char *fmt, ...) {
     va_list ar;
     struct timeval tv;
-#ifdef __APPLE__
+#ifdef __MAC_10_12
     // Apple does not provide a varargs style os_logv
     char logbuf[16 * 1024] = {0};
 #else
@@ -44,7 +44,7 @@ log_error(const char *fmt, ...) {
     if (use_os_log) { bufprint(vsnprintf, fmt, ar); }
     else vfprintf(stderr, fmt, ar);
     va_end(ar);
-#ifdef __APPLE__
+#ifdef __MAC_10_12
     if (use_os_log) os_log(OS_LOG_DEFAULT, "%{public}s", logbuf);
 #endif
     if (!use_os_log) fprintf(stderr, "\n");
@@ -66,7 +66,7 @@ static PyMethodDef module_methods[] = {
 bool
 init_logging(PyObject *module) {
     if (PyModule_AddFunctions(module, module_methods) != 0) return false;
-#ifdef __APPLE__
+#ifdef __MAC_10_12
     if (getenv("KITTY_LAUNCHED_BY_LAUNCH_SERVICES") != NULL) use_os_log = true;
 #endif
     return true;
```

**Comment by kovidgoyal** [comment]
The current kitty codebase only support macOS 10.12 and higher. IIRC there are a couple of forks that stub out the 10.12 specific code to allow it to build and run on 10.11 or you can use one fo the older releases.

**Comment by metayan** [comment]
Keeping the changes to allow running on OS X El Capitan (10.11.6) available in https://github.com/metayan/kitty/tree/osx11
