### ISSUE TITLE
Session startup can no longer create windows

### ISSUE THREAD

**Issue by anicolao** [kovidgoyal/kitty#2908]
The example session startup file in the documentation does not run.

The smallest reproduction is:
```
$ cat - >/tmp/session <<\EOF
> # Create a new OS window
> new_os_window
> # set new window size to 80x25 cells
> os_window_size 80c 25c
> # set the --class for the new OS window
> os_window_class mywindow
> launch sh
> EOF
$ kitty --session /tmp/session 
[223 11:53:44.049033] Traceback (most recent call last):
  File "kitty/main.py", line 343, in main
    _main()
  File "kitty/main.py", line 336, in _main
    run_app(opts, cli_opts, bad_lines)
  File "kitty/main.py", line 158, in __call__
    _run_app(opts, args, bad_lines)
  File "kitty/main.py", line 137, in _run_app
    boss.start(window_id)
  File "kitty/boss.py", line 488, in start
    self.startup_first_child(first_os_window_id)
  File "kitty/boss.py", line 180, in startup_first_child
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "kitty/boss.py", line 201, in add_os_window
    os_window_id = create_os_window(
  File "kitty/config.py", line 750, in get_window_size
    spacing = effective_margin('left') + effective_margin('right')
  File "kitty/config.py", line 744, in effective_margin
    ans: float = getattr(opts.single_window_margin_width, which)
AttributeError: 'WindowSizeOpts' object has no attribute 'single_window_margin_width'
```

**Expected behavior**

An 80x25c window should be created running `sh`.

**Environment details**
Tested on Mac OS X Catalina 10.15.5 but almost certainly portable.

**Additional context**
Bug was probably introduced in c69b8870d with the addition of `effective_margin`

```
diff --git a/kitty/config.py b/kitty/config.py
index 63127009..fc3dde9e 100644
--- a/kitty/config.py
+++ b/kitty/config.py
@@ -23,7 +23,7 @@ from .config_data import all_options, parse_mods, type_convert
 from .constants import cache_dir, defconf, is_macos
 from .key_names import get_key_name_lookup, key_name_aliases
 from .options_stub import Options as OptionsStub
-from .typing import TypedDict
+from .typing import EdgeLiteral, TypedDict
 from .utils import log_error
 
 KeySpec = Tuple[int, bool, int]
@@ -730,12 +730,23 @@ def initial_window_size_func(opts: OptionsStub, cached_values: Dict) -> Callable
             # scaling is not needed on Wayland, but is needed on macOS. Not
             # sure about X11.
             xscale = yscale = 1
+
+        def effective_margin(which: EdgeLiteral) -> float:
+            ans: float = getattr(opts.single_window_margin_width, which)
+            if ans < 0:
+                ans = getattr(opts.window_margin_width, which)
+            return ans
```

**Comment by anicolao** [comment]
I tried just adding `single_window_margin_width` to `WindowSizeOpts` but that just gave me a different traceback. Simplifying `effective_margin` down to 
```
        def effective_margin(which: EdgeLiteral) -> float:
            ans = getattr(opts.window_margin_width, which)
            return ans
```
makes the problem go away, but maybe breaks #688. Though, with this code change two windows are started, a default sized window and the 80x25c window, so maybe it doesn't break 688 whose intention seems to be only single-window use cases and it seems like by definition this type of session startup involves at least 2 os windows.

**Comment by kovidgoyal** [comment]
Leave off the new_os_window at the start if you want only one os window

**Comment by anicolao** [comment]
So the traceback is expected behaviour, if I want two windows?

**Comment by anicolao** [comment]
Oh, sorry I didn't see the commit. Thanks for fixing, I will validate.

**Comment by anicolao** [comment]
Verified that the traceback is fixed by f6ec, thanks.
