### ISSUE TITLE
list keyboard shortcuts

### ISSUE THREAD

**Issue by con-f-use** [kovidgoyal/kitty#2164]
I'd like to list all configured keyboard shortcuts with a kitty command and what they do, including the defaults that come with kitty.

Might already be implemented but I couldn't find a way.

**Comment by kovidgoyal** [comment]
There is no such thing as "what they do" since what they do can be
arbitrary things, including the combination of multiple actions. All
default shortcuts are documented in the kitty documentation, and you can
see what is changed from defaults via 

kitty --debug-config

**Comment by kovidgoyal** [comment]
On and this is where the defaults are documented: https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts

**Comment by con-f-use** [comment]
Thanks for the answer. Perhaps, I wasn't clear enough. I often find myself forgetting the shortcuts while using kitty. I was looking for something like <kbd>Ctrl</kbd>+<kbd>Shfit</kbd>+<kbd>F1</kbd> or <kbd>Ctrl</kbd>+<kbd>Shfit</kbd>+<kbd>?</kbd> to list them from within kitty. In situations where I don't want to or can't open a webpage or where deviating from the defaults.

**Comment by kovidgoyal** [comment]
There is no such functionality, though I suppose one could have the same docs I linked to above added to the kitty man page for local access. Though even there you should have a copy of the html documentation I linked to above installed locally as well.

**Comment by kovidgoyal** [comment]
The next kitty release has basic shortcuts in the kitty man page and also a separate man page for kitty.conf

**Comment by codemedic** [comment]
@kovidgoyal 

Would it be possible to reopen this issue. I wonder if the @con-f-use was after a way to see all current mappings, after customisation.

I agree that for those who do not add custom shortcuts, the man page or online docs are plenty.
But after customising the keys over a period of time, I feel I have lost track of some. Thanks to the uber customisability of kitty, I am able to add shortcuts for all sorts of things, but that means I have to remember all of them. I try my best to keep them intuitive, but...

Would it be possible to have something similar to `:verbose map` in `VIM`? Some of the new generation IDEs too have this. 

Perhaps a `show-map` kitten?

**Comment by kovidgoyal** [comment]
If you want to see the shortcuts (and other settings) you have configured differently from default press ctrl+shift+f6. If you want to browse your configuration press ctrl+shift+f2. I dont see what value a separate kitten for it would bring over these.

**Comment by codemedic** [comment]
Thanks @kovidgoyal Didn't know ctrl+shift+f6 .. thanks.

Perhaps that proves the point. Having a man page or web page where users have to scroll on and on to find which key maps to what ends up being a TL;DR.

If you could extend ctrl+shift+f6 or perhaps another key combination to bring up all keyboard shortcut present, be it default or customised, that would help users who are trying to break into the next level from beginners. If you could educate users about that one key combination very early on in their journey with kitty, it will be help a lot. Perhaps something very intuitive like F1 or kitty_mod+F1. If the interface can have search as well, like the themes UI, then that would take it to the heavens!

**Comment by mivok** [comment]
I came across this issue looking for something like a quick help screen (like pressing ? in github as a quick reminder), but realized that what debug_config does would also work for printing all shortcuts.

For anyone who wants this, I made a kitten that will print a quick overview of all the shortcuts (albeit uncategorized right now).

Create ~/.config/kitty/keymap.py with the following:

```python
# Kitten to print the current list of keyboard shortcuts
#
# Place this in ~/.config/kitty/keymap.py then
# Add "map kitty_mod+/ kitty keymap.py" to your kitty.conf
from kitty import fast_data_types

def main(args):
    return ''

def handle_result(args, answer, target_window_id, boss):
    opts = fast_data_types.get_options()
    keymap = opts.keymap

    output = ["Kitty keyboard mappings", "=" * 23, ""]

    for key, action in keymap.items():
        output.append(f'{key.human_repr} → {action}')
    boss.display_scrollback(boss.active_window, "\n".join(output),
            title="Kitty keyboard mappings", report_cursor=False)
```

then add `map kitty_mod+/ kitten keymap.py` to your kitty.conf. Then CTRL-? (or rather CTRL-SHIFT-/)

**Comment by oplexius** [comment]
Nice kitten @mivok , it was useful to me to quickly check if a key binding I had set up but that wasn't working was actually being registered.

I think on line 4 of each of those code blocks ('# Add "map kitty_mod+/ kitty keymap.py" to your kitty.conf') the second "kitty" should be "kitten" (as you write in the comment) ;).

**Comment by mivok** [comment]
@oplexius oops. I just edited the comment to fix that. Thanks!

**Comment by oplexius** [comment]
So for some reason this made me want to play with kittens :). Here is a kitten to query a specific keyboard shortcut directly on the command line, to see if it exists, and what it is associated with.

Probably not of great use, but I'm posting it here because I had trouble finding simple kitten code examples, and maybe it could serve as an example of a kitten that just outputs plain text to the terminal it was executed from, or for accessing configuration in the main() kitten function. Disclaimer: this is totally naive, I don't know what I'm doing, just treat is as a curiosity ;).

Tested with kitty 0.25.2.

`# Kitty terminal kitten to query if a keyboard shortcut is mapped or not
# Copy code to ~/.config/kitty/keymap_query.py
# To run: kitty +kitten keymap_query <keycombo>
# Keycombos are like in kitty config, e.g.: "ctrl+k", "ctrl+shift+f2"...

from kitty.cli import create_default_opts
from kitty.options.utils import parse_shortcut

def main(args):
    query_keystr = args[1]
    query_key = parse_shortcut(query_keystr)

    opts = create_default_opts()
    keymap = opts.keymap

    if keymap.get(query_key):
        action = keymap[query_key]
        print(f"{query_keystr} is mapped to: {action}\n")
        print(f"https://sw.kovidgoyal.net/kitty/actions/#action-{action.split()[0]}")
        print("(this link will only work for keys bound to default mappable actions)")
    else:
        print(f"{query_keystr} is not mapped")
`

n.b. execute this from a shell, it won't work as a keybinding. fwiw GPL3, like kitty ;).

@mivok , I think there is real value to your kitten, it's easier than going through the docs and config to find the active keybindings. I almost got even more carried away with this to make an uber keymap tool, but I don't want to take your idea. Hope this isn't presumptuous, but feel free to reuse any of this if you develop your kitten any more ;).

**Comment by oplexius** [comment]
So for some reason this made me want to play with kittens :). Here is a kitten to query a specific keyboard shortcut directly on the command line, to see if it exists, and what it is associated with.

Probably not of great use, but I'm posting it here because I had trouble finding simple kitten code examples, and maybe it could serve as an example of a kitten that just outputs plain text to the terminal it was executed from, or for accessing configuration in the main() kitten function. Disclaimer: this is totally naive, I don't know what I'm doing, just treat is as a curiosity ;).

Tested with kitty 0.25.2.

```python
# Kitty terminal kitten to query if a keyboard shortcut is mapped or not
# Copy code to ~/.config/kitty/keymap_query.py
# To run: kitty +kitten keymap_query <keycombo>
# Keycombos are like in kitty config, e.g.: "ctrl+k", "ctrl+shift+f2"...

from kitty.cli import create_default_opts
from kitty.options.utils import parse_shortcut

def main(args):
    query_keystr = args[1]
    query_key = parse_shortcut(query_keystr)

    opts = create_default_opts()
    keymap = opts.keymap

    if keymap.get(query_key):
        action = keymap[query_key]
        print(f"{query_keystr} is mapped to: {action}\n")
        print(f"https://sw.kovidgoyal.net/kitty/actions/#action-{action.split()[0]}")
        print("(this link will only work for keys bound to default mappable actions)")
    else:
        print(f"{query_keystr} is not mapped")
```

n.b. execute this from a shell, it won't work as a keybinding. fwiw GPL3, like kitty ;).


@mivok , I think there is real value to your kitten, it's easier than going through the docs and config to find the active keybindings. I almost got even more carried away with this to make an uber keymap tool, but I don't want to take your idea. Of course, feel free to reuse any of this if you develop your kitten any more :).

**Comment by thatlittleboy** [comment]
@mivok 's kitten no longer works in 0.26.5, as `SingleKey.human_repr` was removed in this commit ce91b6d9d95a680b93cdc742f044466b7b292dfa.

> AttributeError: 'fast_data_types.SingleKey' object has no attribute 'human_repr'

Right now, printing `{key}` gives a repr that looks like 

```
SingleKey(mods=5, key=57352)
```

**Comment by kovidgoyal** [comment]
You get human_repr() by using

```py
from kitty.types import human_repr_of_single_key
```

Note that you have to pass in a value for kitty_mod other than zero if you want the human repr to use kitty_mod instead of the modifiers kitty_mod is mapped to.

**Comment by thatlittleboy** [comment]
Thanks, @kovidgoyal for the hint.

I just changed
```python
"{key.human_repr}"
# to
"{human_repr_of_single_key(key, kitty_mod=5)}"
```
and it works now.

Using kitty_mod=5 because my kitty_mod is Ctrl+Shift. From what I could work out, Shift=1, Opt=2, Ctrl=4, Cmd=8.

**Comment by thatlittleboy** [comment]
For those following this thread, you might also want to include **key sequences** (such as `kitty_mod+p > f` sequence for the `hints` kitten) as well, instead of just keymaps.

---

Here's my kitten working with kitty v0.27.1 (heavily inspired from mivok's kitten shared above):

```python
#!/usr/bin/env python3
"""Kitten to print the current list of keyboard shortcuts (consists of BOTH single keys and key
sequences).
"""

import re
from collections import defaultdict
from typing import Union, Final

from kittens.tui.handler import result_handler
from kitty import fast_data_types
from kitty.boss import Boss
from kitty.options.utils import KeyMap, SequenceMap
from kitty.tab_bar import Formatter as fmt
from kitty.types import Shortcut, mod_to_names

# List of categories and regular expressions to match actions on
categories: Final = {
    "Scrolling": r"(^scroll_|show_scrollback|show_last_command_output)",
    "Tab Management": r"(^|_)tab(_|$)",
    "Window Management": r"(^|_)windows?(_|$)",
    "Layout Management": r"(^|_)layout(_|\b)",
    "Other Shortcuts": r".",
}

ShortcutRepr = str
ActionMap = dict[str, list[ShortcutRepr]]


def main(args: list[str]) -> Union[str, None]:
    pass


@result_handler(no_ui=True)
def handle_result(args: list[str], answer: str, target_window_id: int, boss: Boss):
    opts = fast_data_types.get_options()

    # set up keymaps (single keystrokes)
    keymap: KeyMap = (
        boss.keymap
    )  # same as `opts.keymap`, except with global keymaps removed
    keymap: dict[Shortcut, str] = {
        Shortcut((key,)): action for key, action in keymap.items()
    }
    # set up key sequences (combinations of keystrokes, separated by '>')
    seq_keymap: SequenceMap = opts.sequence_map
    seq_keymap: dict[Shortcut, str] = {
        Shortcut((key, *subseq_keys)): action
        for key, subseq in seq_keymap.items()
        for subseq_keys, action in subseq.items()
    }
    keymap.update(seq_keymap)

    # categorize shortcuts
    # because each action can have multiple shortcuts associated with it, we also attempt to
    # group shortcuts with the same actions together.
    output_categorized: dict[str, ActionMap] = defaultdict(lambda: defaultdict(list))
    for key, action in keymap.items():
        key_repr: ShortcutRepr = key.human_repr(kitty_mod=opts.kitty_mod)
        key_repr = f"{key_repr:<15} {fmt.fg.red}→{fmt.fg.default} {action}"

        for subheader, re_pat in categories.items():
            if re.search(re_pat, action):
                action_map: ActionMap = output_categorized[subheader]
                action_map[action].append(key_repr)
                break
        else:
            emsg = f"No valid subheader found for keymap {key_repr!r}."
            raise ValueError(emsg)

    # print out shortcuts
    output = [
        "Kitty keyboard mappings",
        "=======================",
        "",
        "My kitty_mod is {}.".format("+".join(mod_to_names(opts.kitty_mod))),
        "",
    ]
    for category in categories:
        if category not in output_categorized:
            continue
        output.extend([category, "=" * len(category), ""])
        output.extend(sum(output_categorized[category].values(), []))
        output.append("")

    boss.display_scrollback(
        boss.active_window,
        "\n".join(output),
        title="Kitty keyboard mappings",
        report_cursor=False,
    )
```

There's a lot of extra fluff (so pick and choose to implement the ideas you want), but a few key differences / changes from earlier implementations:
- added support for key sequences, such as `kitty_mod+p > f` mentioned above
- "sort"-sorted the shortcuts based on similar actions (there are multiple ways to achieve the same action in kitty, I've attempted to group them together), rather than purely sorting by shortcuts </br> <image src="https://user-images.githubusercontent.com/30731072/230767745-d0622c07-70eb-490a-829c-8d7a5545ce5b.png" width="230">
- added a header to print out my `kitty_mod` (just in case I forgot :))

**Comment by ershov** [comment]
Hi,
Please check out my take on displaying the full config: https://github.com/ershov/kitty_config

<img src="https://user-images.githubusercontent.com/449936/247107031-95625fea-0533-4312-bbd6-caf47479990f.png">

<img src="https://user-images.githubusercontent.com/449936/247107180-b2416091-8eb1-40cd-90a1-8052ce7bbbf8.png">

**Comment by nicoandmee** [comment]
> Hi, Please check out my take on displaying the full config: [ershov/kitty_config](https://github.com/ershov/kitty_config)
> 
> ![](https://user-images.githubusercontent.com/449936/247107031-95625fea-0533-4312-bbd6-caf47479990f.png)
> 
> ![](https://user-images.githubusercontent.com/449936/247107180-b2416091-8eb1-40cd-90a1-8052ce7bbbf8.png)

👍🏾 thanks for this!

**Comment by rmacklin** [comment]
@thatlittleboy Any chance you've updated your kitten to work with the latest version of kitty (v0.32.1)?

**Comment by eliliam** [comment]
@thatlittleboy I came across your script and it looks like exactly what I'm looking for, however when I try to activate it I am met with the following error:
```
Key action failed


kitten keymap.py
cannot import name 'SequenceMap' from 'kitty.options.utils' (/usr/bin/../lib/kitty/kitty/options/utils.py)

Press e to see detailed traceback or any other key to exit
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1631, in combine
    if self.dispatch_action(actions[0], window_for_dispatch, dispatch_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1582, in dispatch_action
    passthrough = f(*key_action.args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1975, in kitten
    self.run_kitten_with_metadata(kitten, kargs, window=self.window_for_dispatch)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1894, in run_kitten_with_metadata
    end_kitten = create_kitten_handler(kitten, orig_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 89, in create_kitten_handler
    m = import_kitten_main_module(config_dir, kitten)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 62, in import_kitten_main_module
    exec(code, g)
  File "/home/eli/.config/kitty/keymap.py", line 13, in <module>
    from kitty.options.utils import KeyMap, SequenceMap
ImportError: cannot import name 'SequenceMap' from 'kitty.options.utils' (/usr/bin/../lib/kitty/kitty/options/utils.py)
```

**Comment by monkeyxite** [comment]
> @thatlittleboy I came across your script and it looks like exactly what I'm looking for, however when I try to activate it I am met with the following error:
> 
> ```
> Key action failed
> 
> 
> kitten keymap.py
> cannot import name 'SequenceMap' from 'kitty.options.utils' (/usr/bin/../lib/kitty/kitty/options/utils.py)
> 
> Press e to see detailed traceback or any other key to exit
> Traceback (most recent call last):
>   File "/usr/bin/../lib/kitty/kitty/boss.py", line 1631, in combine
>     if self.dispatch_action(actions[0], window_for_dispatch, dispatch_type):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/../lib/kitty/kitty/boss.py", line 1582, in dispatch_action
>     passthrough = f(*key_action.args)
>                   ^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/../lib/kitty/kitty/boss.py", line 1975, in kitten
>     self.run_kitten_with_metadata(kitten, kargs, window=self.window_for_dispatch)
>   File "/usr/bin/../lib/kitty/kitty/boss.py", line 1894, in run_kitten_with_metadata
>     end_kitten = create_kitten_handler(kitten, orig_args)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/../lib/kitty/kittens/runner.py", line 89, in create_kitten_handler
>     m = import_kitten_main_module(config_dir, kitten)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/../lib/kitty/kittens/runner.py", line 62, in import_kitten_main_module
>     exec(code, g)
>   File "/home/eli/.config/kitty/keymap.py", line 13, in <module>
>     from kitty.options.utils import KeyMap, SequenceMap
> ImportError: cannot import name 'SequenceMap' from 'kitty.options.utils' (/usr/bin/../lib/kitty/kitty/options/utils.py)
> ```
> 
> #### System Info
> OS: Arch Linux Kitty version 0.36.4 System Python version: 3.12.6

Same error for MacOS with Kitty 0.37.0

**Comment by thatlittleboy** [comment]
@rmacklin @eliliam @monkeyxite 

I've updated to work with kitty 0.36.4, should work with 0.37 as well (but haven't tested it).

Couple of key changes:
- Keyboard modes were introduced (see https://sw.kovidgoyal.net/kitty/mapping/#modal-mappings); I've opted to categorize modes as their own category, you may modify the script to fit your own requirements.
- Bolded the category names as well as the mode names

```python
#!/usr/bin/env python3
"""Kitten to print the current list of keyboard shortcuts (consists of BOTH single keys and key
sequences).
"""

import re
from collections import defaultdict
from collections.abc import Sequence
from typing import Final, Union, TypeAlias

from kittens.tui.handler import result_handler
from kitty import fast_data_types
from kitty.boss import Boss
from kitty.options.types import Options as KittyOpts
from kitty.options.utils import KeyMap, KeyboardMode, KeyDefinition
from kitty.tab_bar import Formatter as fmt
from kitty.types import Shortcut, mod_to_names

# List of categories and regular expressions to match actions on
# Keyboard modes are categorized into their own category
categories = {
    "Scrolling": r"(^scroll_|show_scrollback|show_last_command_output)",
    "Tab Management": r"(^|_)tab(_|$)",
    "Window Management": r"(^|_)windows?(_|$)",
    "Layout Management": r"(^|_)layout(_|\b)",
    "Other Shortcuts": r".",
    # "Mode (xxx)": ...,
}

Shortcut2Defn: TypeAlias = dict[Shortcut, str]
ShortcutRepr: TypeAlias = str
ActionMap: TypeAlias = dict[str, list[ShortcutRepr]]


def main(args: list[str]) -> Union[str, None]:
    pass


@result_handler(no_ui=True)
def handle_result(args: list[str], answer: str, target_window_id: int, boss: Boss):
    opts: KittyOpts = fast_data_types.get_options()

    output_categorized: dict[str, ActionMap] = defaultdict(lambda: defaultdict(list))
    for mode in opts.keyboard_modes.values():
        mode: KeyboardMode
        mode_name: str = mode.name or "default"
        mode_keymap: KeyMap = mode.keymap

        # set up keymaps (single keystrokes) + key sequences (combinations of keystrokes)
        key_mappings: Shortcut2Defn = {}
        for key, definitions in mode_keymap.items():
            # key: SingleKey
            definitions: Sequence[KeyDefinition]

            for defn in definitions:
                action = defn.human_repr()
                if defn.is_sequence:
                    key_mappings[Shortcut((defn.trigger,) + defn.rest)] = action
                else:
                    key_mappings[Shortcut((key,))] = action

        # categorize the default mode shortcuts
        # because each action can have multiple shortcuts associated with it, we also attempt to
        # group shortcuts with the same actions together.
        for key, action in key_mappings.items():
            key_repr: ShortcutRepr = key.human_repr(kitty_mod=opts.kitty_mod)
            key_repr = f"{key_repr:<18} {fmt.fg.red}→{fmt.fg.default}"
            if match := re.search(r"^push_keyboard_mode (\w+)$", action):
                # bold the mode name if found
                action_fmt = (
                    f"push_keyboard_mode {fmt.bold}{match.group(1)}{fmt.nobold}"
                )
                key_repr = f"{key_repr} {action_fmt}"
            else:
                key_repr = f"{key_repr} {action}"

            if mode_name != "default":
                mn = f"Mode {mode_name}"
                categories[mn] = None  # register this mode as a valid "category"
                output_categorized[mn][action].append(key_repr)
                continue

            for subheader, re_pat in categories.items():
                if re.search(re_pat, action):
                    action_map: ActionMap = output_categorized[subheader]
                    action_map[action].append(key_repr)
                    break
            else:
                emsg = f"No valid subheader found for keymap {key_repr!r}."
                raise ValueError(emsg)

    # print out shortcuts
    output = [
        "=======================",
        "Kitty keyboard mappings",
        "=======================",
        "",
        "My kitty_mod is {}.".format("+".join(mod_to_names(opts.kitty_mod))),
        "",
    ]
    for category in categories:
        if category not in output_categorized:
            continue
        output.extend([f"{fmt.bold}{category}{fmt.nobold}", "=" * len(category), ""])
        output.extend(sum(output_categorized[category].values(), []))
        output.append("")

    boss.display_scrollback(
        boss.active_window,
        "\n".join(output),
        title="Kitty keyboard mappings",
        report_cursor=False,
    )
```

<img src="https://github.com/user-attachments/assets/578f9e6b-1649-42cb-8844-1ecc0ddd73bd" width=500>
<img src="https://github.com/user-attachments/assets/13fc14bb-f3c9-4010-b785-db8d1204d295" width=500>

**Comment by markfaine** [comment]
> [@rmacklin](https://github.com/rmacklin) [@eliliam](https://github.com/eliliam) [@monkeyxite](https://github.com/monkeyxite)
> 
> I've updated to work with kitty 0.36.4, should work with 0.37 as well (but haven't tested it).
> 
Any idea how I can get this output to fzf?  Thanks, it looks great!
nm, I got it:

```
PAGER="fzf --ansi" kitty
```

**Comment by iandol** [comment]
@thatlittleboy 


> I've updated to work with kitty 0.36.4, should work with 0.37 as well (but haven't tested it).

This works when run via a key-mapping, but I tried to run this as a kitten command and get no output: `kitty +kitten yourcode.py` — `handle_result` is never called only `main` runs, can this kitten be made to optionally output to the terminal. I tried to add an arg to manually call `handle_result` but neither ChatGPT (passed the kitty kitten API docs) nor my own blind hacking (not a python person) got anywhere. My use case is I want to pipe to `fzf`...

@markfaine — how exactly did you get fzf to work, are you launching a new kitty

**Comment by edwinclement08** [comment]
@iandol, I used the following to get the list as a one-off effort.

Copied the steps from https://stackoverflow.com/questions/25317125/less-viewer-copy-all-the-lines-to-clipboard
```
less doesn't have a clipboard, but you may be able to get it to output what's stored in its buffers to a new file. This will only work if the entire contents of the file are buffered:

    Type g to go to the top of the file
    Type | (that's a pipe character, not an L or I) to indicate that you want to output to a pipe
    Type $ to indicate that you want the output content to go to the end of the file
    Type dd of=/path/to/new/file and press Enter

The dd command will take the piped data and save it to the file passed to the of= argument.
```

**Comment by iandol** [comment]
Yes, piping out to a physical file is a useful workaround, thank you!

**Comment by iandol** [comment]
> [@iandol](https://github.com/iandol), I used the following to get the list as a one-off effort.

Yes, piping to a physical file to use later is a useful workaround, thank you!

**Comment by markfaine** [comment]
> [@markfaine](https://github.com/markfaine) — how exactly did you get fzf to work, are you launching a new kitty

Yes, you are correct.  I didn't realize at the time but the only way the posted solution works is if I launch from kitty.  I am testing setting the PAGER environment variable before launching kitty but so far it hasn't worked.

**Comment by kovidgoyal** [comment]
There is now a command_palette action implemented in master.

**Comment by iandol** [comment]
Awesome, thank you @kovidgoyal !!!
