### ISSUE TITLE
Fails to build on Fedora Rawhide (Python 3.7)

### ISSUE THREAD

**Issue by gagbo** [kovidgoyal/kitty#714]
I suppose that given enough time I'll be able to sort it out, I just wanted to tell about the issue I have packaging kitty in my copr.

Fedora project is pushing Python 3.7 for Fedora 29 and this effort led to recently rebuilding a lot of packages in Rawhide to prepare for this. Since then I can build the kitty package for Fedora 28 but Fedora 29 will not build. I suppose the problem comes from the change in Python but it may be something else, I'm not entirely sure yet.

Here is the [full build log](https://copr-be.cloud.fedoraproject.org/results/gagbo/kitty-latest/fedora-rawhide-x86_64/00775700-kitty/build.log.gz) where the error I get is specifically : 

```
BUILDSTDERR: gcc -MMD -D_XOPEN_SOURCE=700 -DDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=11 -Wextra -Wno-missing-field-initializers -Wall -std=c99 -pedantic-errors -Werror -g3 -Og -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -fPIC -pthread -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/python3.7m -I/usr/include/python3.7m -c /builddir/build/BUILD/kitty-0.11.2/kitty/glfw.c -o /builddir/build/BUILD/kitty-0.11.2/build/fast_data_types-glfw.c.o/builddir/build/BUILD/kitty-0.11.2/kitty/freetype.c: In function "face_from_descriptor":
BUILDSTDERR: /builddir/build/BUILD/kitty-0.11.2/kitty/freetype.c:176:16: error: assignment discards "const" qualifier from pointer target type [-Wdiscarded-qualifiers]
BUILDSTDERR:      } else key = conv(t); \
BUILDSTDERR:                 ^
BUILDSTDERR: /builddir/build/BUILD/kitty-0.11.2/kitty/freetype.c:182:5: note: in expansion of macro "D"
BUILDSTDERR:      D(path, PyUnicode_AsUTF8, false);
BUILDSTDERR:      ^
```

Whereas on F28 I don't have any issue ( link to the [log](https://copr-be.cloud.fedoraproject.org/results/gagbo/kitty-latest/fedora-28-x86_64/00775700-kitty/build.log.gz) )

PS : Rawhide is on `gcc (GCC) 8.1.1 20180626 (Red Hat 8.1.1-4)`, no idea yet of the gcc version currently in F28
