### ISSUE TITLE
Switching key combination stops input

### ISSUE THREAD

**Issue by Dtesch9** [kovidgoyal/kitty#9658]
**Describe the bug**

Switching key combination worked smoothly until last release, I scroll on nvim with ctrl + j and ctrl + k, so if I'm moving my cursor with j and I press ctrl it would trigger scroll, if I release one of the keys, such as ctrl and keep holding j, it would still be moving my cursor down, now that behavior stopped out of a sudden, alacritty also have this exactly behavior as kitty used to have until 0.45.0, and stopped working at 0.46.0

**To Reproduce**

1. On version 0.45.0, hold ctrl + j, note that it's going to next line, if you release ctrl, j key is going to keep being input, if you hold ctrl again it would input new line, since you are still holding j.

2. Do step one again on latest version 0.46.0, check it's not working

**Environment details**
```
kitty 0.46.0 created by Kovid Goyal
Linux dtesch-pc 6.18.17-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 12 Mar 2026 14:46:13 +0000 x86_64
Arch Linux 6.18.17-1-lts (/dev/tty)
Running under: Wayland (GNOME Shell 49.4) missing: blur server_side_decorations layer_shell icon
OpenGL: '3.1.0 NVIDIA 590.48.01' Detected version: 3.1
Frozen: False
Fonts:
  medium: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
    bold: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
  italic: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
      bi: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
System color scheme: dark. Applied color theme type: none
Loaded config files:
  /home/dtesch/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       yes
background_opacity         0.97
bold_font                  family="Fira Code" style='Light'
bold_italic_font           family="Fira Code" style='Light'
cursor_text_color          None
dynamic_background_opacity True
font_family                family="Fira Code" style='Light'
font_size                  10.5
italic_font                family="Fira Code" style='Light'
listen_on                  unix:/tmp/mykitty
Added shortcuts:
        ctrl+' →  send_text all \x1b[39;5u
        ctrl+, →  send_text all \x1b[44;5u
        ctrl+- →  send_text all \x1b[45;5u
        ctrl+. →  send_text all \x1b[46;5u
        ctrl+/ →  send_text all \x1b[47;5u
        ctrl+; →  send_text all \x1b[59;5u
        ctrl+[ →  send_text all \x1b[91;5u
        ctrl+] →  send_text all \x1b[93;5u
        ctrl+` →  send_text all \x1b[96;5u
        ctrl+page_down →  move_tab_forward
        ctrl+page_up →  move_tab_backward
        ctrl+~ →  send_text all \x1b[126;5u
        ctrl+´ →  send_text all \x1b[180;5u
        ctrl+ç →  send_text all \x1b[231;5u
Changed shortcuts:
        kitty_mod+, →  previous_tab
        kitty_mod+. →  next_tab
        kitty_mod+h →  no-op
        kitty_mod+j →  no-op
        kitty_mod+k →  no-op

// Older working version

kitty 0.45.0 created by Kovid Goyal
Linux dtesch-pc 6.18.17-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 12 Mar 2026 14:46:13 +0000 x86_64
Arch Linux 6.18.17-1-lts (/dev/tty)
Running under: Wayland (GNOME Shell 49.4) missing: blur server_side_decorations layer_shell icon
OpenGL: '3.1.0 NVIDIA 590.48.01' Detected version: 3.1
Frozen: False
Fonts:
  medium: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
    bold: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
  italic: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
      bi: FiraCode-Light: /usr/share/fonts/TTF/FiraCode-Light.ttf:0
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
System color scheme: dark. Applied color theme type: none
Loaded config files:
  /home/dtesch/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       yes
background_opacity         0.97
bold_font                  family="Fira Code" style='Light'
bold_italic_font           family="Fira Code" style='Light'
cursor_text_color          None
dynamic_background_opacity True
font_family                family="Fira Code" style='Light'
font_size                  10.5
italic_font                family="Fira Code" style='Light'
listen_on                  unix:/tmp/mykitty
Added shortcuts:
        ctrl+' →  send_text all \x1b[39;5u
        ctrl+, →  send_text all \x1b[44;5u
        ctrl+- →  send_text all \x1b[45;5u
        ctrl+. →  send_text all \x1b[46;5u
        ctrl+/ →  send_text all \x1b[47;5u
        ctrl+; →  send_text all \x1b[59;5u
        ctrl+[ →  send_text all \x1b[91;5u
        ctrl+] →  send_text all \x1b[93;5u
        ctrl+` →  send_text all \x1b[96;5u
        ctrl+page_down →  move_tab_forward
        ctrl+page_up →  move_tab_backward
        ctrl+~ →  send_text all \x1b[126;5u
        ctrl+´ →  send_text all \x1b[180;5u
        ctrl+ç →  send_text all \x1b[231;5u
Changed shortcuts:
        kitty_mod+, →  previous_tab
        kitty_mod+. →  next_tab
        kitty_mod+h →  no-op
        kitty_mod+j →  no-op
        kitty_mod+k →  no-op
```

**Comment by kovidgoyal** [comment]
There have been no changes to key input in 0.46 other than a timeout for
multi key shortcuts, which is not applicable here. And running

kitty --config=NONE kitten show-key -m kitty

And then holding down j I see j REPEAT events, as expected. Then
pressing ctrl while keep j held shows me repeated ctrl+j events, as
expected. Leaving ctrl goes back to repeated j events, as expected. So
if you are having issues its likely with nvim not kitty, as the show-key
test shows that kitty is generating the expected events.

**Comment by kovidgoyal** [comment]
Actually I just noticed you are on GNOME. GNOME implements compositor side repeat events, which kitty recently gained support for. So repeat behavior is dependent on GNOME. You can see this easily by running kitty with --debug-input, GNOME will stop sending repeat events when you press another key. So either use a different compositor or complain to the GNOME developers.

**Comment by Dtesch9** [comment]
> Actually I just noticed you are on GNOME. GNOME implements compositor side repeat events, which kitty recently gained support for. So repeat behavior is dependent on GNOME. You can see this easily by running kitty with --debug-input, GNOME will stop sending repeat events when you press another key. So either use a different compositor or complain to the GNOME developers.

Appreciate your fast replying, glad it still working on other compositors.

Switching to 0.45 works as usual, I did not move away from GNOME, just downgraded kitty from 0.46 to 0.45 and it works again.

If it was all GNOME compositor issue, it wouldn't be working on 0.45 as well right? that's what got me confused.

Thanks again for the feedback and the debugging advice.

**Comment by zeehjr** [comment]
Hey guys, just a heads up that I'm also facing that issue with 0.46.
- I'm also using GNOME
- 0.45 works fine
- Alacritty and foot are working fine

I'm not into opengl things, but it seems to be related to this PR: https://github.com/kovidgoyal/kitty/issues/9374

@kovidgoyal do you have any suggestions for investigating that? I can't understand why foot (wayland-only terminal) would work correctly in GNOME and kitty doesn't.
So maybe it's related to OpenGL <-> GNOME or foot does not implements anything related to GNOME.

I was about to build with this PR reverted, but I couldn't find the build instructions anywhere. I'm gonna try it later.

EDIT: just found it! https://sw.kovidgoyal.net/kitty/build/

Thanks!

**Comment by Dtesch9** [comment]
Reverting https://github.com/yonasBSD/kitty/commit/c389f4d5b8230a551fb79fc1c81a823c4df7f2e4 fixes it!

**Comment by Lucas-Loureiro** [comment]
+1

**Comment by kovidgoyal** [comment]
As I said, kitty recently got support for compositor side key repeats.
Now repeat behavior depends on the compositor. foot and whatever dont
yet support this, when they do, they will behave the same. This needs to
be fixed *in the compositor* or use a different compositor either one
that doesnt support compositor side key repeats or one that does but
with behavior that suits you. An example of  a compositor that both supports key repeat and does not suffer from this issue is kwin. You need to report this behavior to the mutter developers and get it fixed there.

**Comment by Dtesch9** [comment]
Updates, I have opened an issue on mutter, they have addressed [the issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/4675), hopefully we'll have a fix soon enough, thanks @kovidgoyal
