### ISSUE TITLE
Kitty doesn't build on macOS 10.12 and 10.13 (suggest braces around initialization of subobject)

### ISSUE THREAD

**Issue by judaew** [kovidgoyal/kitty#3530]
**Describe the bug**

Kitty [doesn't build](https://trac.macports.org/ticket/62732) on macOS [10.12](https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/144701/steps/install-port/logs/stdio) and [10.13](https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/109239/steps/install-port/logs/stdio).

```
kitty/child-monitor.c:1502:35: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    PollFD fds[PEER_LIMIT + 8] = {0};
                                  ^
                                  {}
1 error generated.
```

I think removing the `-Werror` compiler flag from here (setup.py) will likely fix this.

https://github.com/kovidgoyal/kitty/blob/19524a4459e8fa65bf064cc7e1774dd3f4ddef1e/setup.py#L291-L293

If this compiler flag is necessary, then I think it would be a good option to implement a workaround build without this flag. For example, as an option with an argument like `--update-check-interval`. This been would a better instead of [patching](https://github.com/macports/macports-ports/pull/10775).

**Comment by kovidgoyal** [comment]
This is already fixed in master. I want kitty to always build with zero
compiler warnings. That is a design goal. So -Werror stays. As for
adding a build option to disable it, sure.

**Comment by judaew** [comment]
Thanks so much
