### ISSUE TITLE
Background opacity/blur broken in 0.29.1

### ISSUE THREAD

**Issue by amaanq** [kovidgoyal/kitty#6500]
**Describe the bug**

Blur/opacity in KDE X11 broken in 0.29.1

**To Reproduce**
1. Use Kitty 0.29.1 with opacity set and some blur applied in KDE (force-blur script does this well)

**Screenshots**
No blur when there should be

**Environment details**
```
kitty 0.28.1 created by Kovid Goyal
Linux archmain 6.4.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 24 Jul 2023 20:19:56 +0000 x86_64
Arch Linux 6.4.6-zen1-1-zen (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/amaanq/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color        None
active_tab_font_style      (True, False)
background_opacity         0.7
bell_on_tab                
copy_on_select             clipboard
cursor                     None
cursor_blink_interval      0.75
cursor_shape               2
cursor_stop_blinking_after 30.0
dynamic_background_opacity True
enable_audio_bell          False
font_family                Monaco
initial_window_height      (600, 'px')
initial_window_width       (800, 'px')
input_delay                1
remember_window_size       False
repaint_delay              6
scrollback_lines           100000
shell_integration          frozenset({'enabled', 'no-cursor'})
strip_trailing_spaces      always
sync_to_monitor            False
window_border_width        (1.0, 'px')
Colors:
	active_tab_background      #26233a   
	active_tab_foreground      #e0def4   
	background                 #191724   
	color0                     #26233a   
	color1                     #eb6f92   
	color10                    #31748f   
	color11                    #f6c177   
	color12                    #9ccfd8   
	color13                    #c4a7e7   
	color14                    #ebbcba   
	color15                    #e0def4   
	color2                     #31748f   
	color3                     #f6c177   
	color4                     #9ccfd8   
	color5                     #c4a7e7   
	color6                     #ebbcba   
	color7                     #e0def4   
	color8                     #6e6a86   
	color9                     #eb6f92   
	cursor_text_color          #e0def4   
	foreground                 #e0def4   
	inactive_border_color      #403d52   
	inactive_tab_background    #191724   
	inactive_tab_foreground    #6e6a86   
	selection_background       #403d52   
	selection_foreground       #e0def4   
	tab_bar_background         #3a3752   
	url_color                  #c4a7e7   

Important environment variables seen by the kitty process:
	PATH                                /home/amaanq/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                C.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                amaanq
	XCURSOR_SIZE                        24
	XDG_DATA_DIRS                       /home/amaanq/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CONFIG_DIRS                     /home/amaanq/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    x11
	XDG_VTNR                            2

```

**Additional context**
I believe just setting background_opacity can cause this bug. I have bisected to find a potential spot for the bug, bisect log:

```
git bisect start
# status: waiting for both good and bad commits
# bad: [22dd8ecb62169f713048431ba5663ac16562af7b] Apparently people out there want to build kitty with rc Go versions
git bisect bad 22dd8ecb62169f713048431ba5663ac16562af7b
# status: waiting for good commit(s), bad commit known
# good: [07bcc5ba61260a6953121f63416c3cfc12cadb46] version 0.28.1
git bisect good 07bcc5ba61260a6953121f63416c3cfc12cadb46
# skip: [4c5f4c4baf0e4c6dd87960a2030489bf2cbd8e1e] Apparently Python 3.12 no longer raises FileNotFoundError when closing a deleted file
git bisect skip 4c5f4c4baf0e4c6dd87960a2030489bf2cbd8e1e
# skip: [d3fc8a2897b897d3d1f57bf8078b7d3c63fd54f6] Remove a bunch of option processing code and directly define the threshold in the shader
git bisect skip d3fc8a2897b897d3d1f57bf8078b7d3c63fd54f6
# skip: [aa0642d3e38e1e7303cd4b5aca5b7e6f1f0248f8] Show shader filename in compilation error messages
git bisect skip aa0642d3e38e1e7303cd4b5aca5b7e6f1f0248f8
# skip: [624007c7aa2fd725f8f55119971fc39cc3febeaf] Refuse to read image files in /proc /sys and /dev
git bisect skip 624007c7aa2fd725f8f55119971fc39cc3febeaf
# skip: [b96a261a3538b98614a798fb6bc2093319a8054f] ...
git bisect skip b96a261a3538b98614a798fb6bc2093319a8054f
# skip: [7f6f1f9a5dac301b9f977e0d1a53c487c5cad9aa] Fix a regression in 0.28.0 that caused a buffer overflow when clearing the screen
git bisect skip 7f6f1f9a5dac301b9f977e0d1a53c487c5cad9aa
# bad: [28fbab347607806235439eb976ae6c08e3e1b6e6] ...
git bisect bad 28fbab347607806235439eb976ae6c08e3e1b6e6
# bad: [2ce5ad63956bd88d83429b359debf87d703f4b20] Fix regression that broke display of error on failure to open URL
git bisect bad 2ce5ad63956bd88d83429b359debf87d703f4b20
# skip: [9f377c5ccbee90d463f293bae8527b82249f04c1] Cache shader source code loading
git bisect skip 9f377c5ccbee90d463f293bae8527b82249f04c1
# skip: [af65b68ac3eec07bc81d8cdfb046cc2bc10998c5] Make timestamps.js re-useable
git bisect skip af65b68ac3eec07bc81d8cdfb046cc2bc10998c5
# skip: [52afc79476d98cec2fc2c81e3ea3adeb98a9ddb9] Fix re-using an image id for an animated image for a still image causing a crash
git bisect skip 52afc79476d98cec2fc2c81e3ea3adeb98a9ddb9
# skip: [8d1facd84dbb3c9fdd770969c8844a76f544e868] Bump github.com/shirou/gopsutil/v3 from 3.23.3 to 3.23.5
git bisect skip 8d1facd84dbb3c9fdd770969c8844a76f544e868
# good: [af8db1eb8fff0f645c234420ec8ecb8915ebe7ee] Add an example for how to get a single color from @ get-colors
git bisect good af8db1eb8fff0f645c234420ec8ecb8915ebe7ee
# bad: [94e2aeb38c723ac1e2f27cbd04065c6b0c07e8f3] ...
git bisect bad 94e2aeb38c723ac1e2f27cbd04065c6b0c07e8f3
# good: [5f8610f7bc8ed21d54c13ce66ece3545ce3bb59f] macOS: Add a new value titlebar-and-corners for :opt:hide_window_decorations that emulates the behavior of hide_window_decorations yes in older versions of kitty
git bisect good 5f8610f7bc8ed21d54c13ce66ece3545ce3bb59f
# bad: [e3633033593597159597dc5ad05d16f6c74c4134] Nicer error message for pwfile owner/permission mismatch
git bisect bad e3633033593597159597dc5ad05d16f6c74c4134
# bad: [97b073fd8c56e6610b7c0920f21646bac6a4aaa7] GNOME: Fix wayland_titlebar_color not being applied until the color is changed at least once
git bisect bad 97b073fd8c56e6610b7c0920f21646bac6a4aaa7
# good: [9e0e23ae993ff9c577ee37e51803208a653674db] macOS: Fix a regression that caused the titlebar to be translucent even for non-translucent windows
git bisect good 9e0e23ae993ff9c577ee37e51803208a653674db
# first bad commit: [97b073fd8c56e6610b7c0920f21646bac6a4aaa7] GNOME: Fix wayland_titlebar_color not being applied until the color is changed at least once

97b073fd8c56e6610b7c0920f21646bac6a4aaa7 is the first bad commit
commit 97b073fd8c56e6610b7c0920f21646bac6a4aaa7
Author: Kovid Goyal <kovid@kovidgoyal.net>
Date:   Wed Jul 12 10:38:33 2023 +0530

    GNOME: Fix wayland_titlebar_color not being applied until the color is changed at least once

    Fixes #6447

 docs/changelog.rst |  2 ++
 kitty/glfw.c       | 30 +++++++++++++++---------------
 2 files changed, 17 insertions(+), 15 deletions(-)
 ```

**Comment by amaanq** [comment]
This patch fixes it, though I haven't spent enough time to understand the internals well

```diff
diff --git a/kitty/glfw.c b/kitty/glfw.c
index db73487dd..4fba31fb7 100644
--- a/kitty/glfw.c
+++ b/kitty/glfw.c
@@ -1151,8 +1151,6 @@ create_os_window(PyObject UNUSED *self, PyObject *args, PyObject *kw) {
     init_window_chrome_state(&w->last_window_chrome, OPT(background), w->is_semi_transparent, w->background_opacity);
 #ifdef __APPLE__
     apply_window_chrome_state(w->handle, w->last_window_chrome, width, height, OPT(hide_window_decorations) != 0);
-#else
-    apply_window_chrome_state(w->handle, w->last_window_chrome, width, height, false);
 #endif
     // Update window state
     // We do not call glfwWindowHint to set GLFW_MAXIMIZED before the window is created.
```

**Comment by kovidgoyal** [comment]
blur in KDE/X11 is now builtin, see 

the background_blur option. As far as I know it works fine, if not let
me know.

**Comment by amaanq** [comment]
Oh gotcha, thank you! That does in fact work well, should've checked the docs a bit more :)

**Comment by Lesnock** [comment]
How does this config works?
I'm trying to get background blur, but without success:

Here is my config:
```
background_opacity 0.9
background_blur 64
linux_display_server x11
dynamic_background_opacity yes
```

Here is the result (only the opacity is being applied):
![image](https://github.com/kovidgoyal/kitty/assets/19783675/1529a65c-5c3c-4e3a-ad58-c78e357f80ce)

**Comment by amaanq** [comment]
I just set mine to 1, the blur portion depends on your DE and KDE works the best in my experience, your issue lies there

**Comment by Lesnock** [comment]
What you mean by DE and KDE?
Sorry, i'm really a noob at this

**Comment by amaanq** [comment]
your desktop environment, sorry I can't help further as that's too much to explain here.

**Comment by Xenfo** [comment]
I'm running Hyprland and blur isn't working for me (the the background is already blurred a tiny bit even with the option off). Increasing blur does nothing.

**Comment by kovidgoyal** [comment]
Read the docs of the background_blur option

**Comment by Xenfo** [comment]
I've read them and it's stated that X11 is supported, which means it should be supported by XWayland. Unless XWayland doesn't include blur support?

**Comment by kovidgoyal** [comment]
The docs state it is supported in macOS and KDE/X11 aka KDE running
under X11

**Comment by Xenfo** [comment]
Ah alright, thanks. I misunderstood the docs. Thought that you were trying to say it would work under KDE or X11.

**Comment by serif** [comment]
I was using the Force Blur KWin script in KDE/X11 and getting blur only on 2nd, 3rd, etc. Kitty windows opened with ctrl+shift+n, but never the initial window. Adding that detail here in case it's helpful, but it's probably irrelevant since just setting `background_blur 1` along with my preference of `background_opacity 0.8` fixed the issue. I've removed the "kitty" entry from the Force Blur script since it's no longer necessary. Maybe the Force Blur keywords will help others find this.

Thank you @kovidgoyal for the best terminal in the world, and @amaanq for the specific value suggestion.
