### ISSUE TITLE
AttributeError: module 're' has no attribute 'Match'

### ISSUE THREAD

**Issue by Mike-7b7** [kovidgoyal/kitty#3010]
I have defined a keyboard shortcut in kitty.conf:                                                                                                                                            
                                                                                                                                                                                               
      map alt+f               kitten hints --type path --program @                                                                                                                             
                                                                                                                                                                                               
  Prior to version 0.19.0 this works well.                                                                                                                                                     
                                                                                                                                                                                               
  After upgrading to 0.19.0 pressing alt+f produces this error message:                                                                                                                        
                                                                                                                                                                                               
      Traceback (most recent call last):                                                                                                                                                       
        File ".../kitty/kitty/launcher/../../kittens/hints/main.py", line 466, in run                                                                                                          
          text, hyperlinks = process_hyperlinks(text)                                                                                                                                          
        File ".../kitty/kitty/launcher/../../kittens/hints/main.py", line 437, in process_hyperlinks                                                                                           
          def process_hyperlink(m: re.Match) -> str:                                                                                                                                           
      AttributeError: module 're' has no attribute 'Match'                                                                                                                                     
      Press Enter to quit.                                                                                                                                                                     
                                                                                                                                                                                               
  It can be solved by editing file kitty/kittens/hints/main.py:                                                                                                                                
                                                                                                                                                                                               
  Wrong line 437:                                                                                                                                                                              
                                                                                                                                                                                               
      def process_hyperlink(m: re.Match) -> str:                                                                                                                                               
                                                                                                                                                                                               
  Corrected:                                                                                                                                                                                   
                                                                                                                                                                                               
      def process_hyperlink(m: re.match) -> str:                                                                                                                                               
                                                                                                                                                                                               
  Thank you for this wonderful terminal emulator!                                                                                                                                              
  Mike
