### ISSUE TITLE
Compile on macOS 10.15.3 broken on 'PycInvalidationMode'

### ISSUE THREAD

**Issue by lexpierce** [kovidgoyal/kitty#2412]
Compilation error:
```
python3 setup.py kitty.app 
CC: clang (4, 2)
[54/54] Compiling kitty/gl-wrapper.c ... done
[5/5] Linking kittens/choose/subseq_matcher ... done
Traceback (most recent call last):
  File "setup.py", line 1054, in <module>
    main()
  File "setup.py", line 1049, in main
    package(args, bundle_type='macos-package')
  File "setup.py", line 893, in package
    compile_python(libdir)
  File "setup.py", line 731, in compile_python
    workers=num_workers, invalidation_mode=py_compile.PycInvalidationMode.UNCHECKED_HASH
AttributeError: module 'py_compile' has no attribute 'PycInvalidationMode'
make: *** [app] Error 1
```

```
$ uname -a
Darwin hostname.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

Latest XCode.

```
$ python3 -VV
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```
