### ISSUE TITLE
startup_session crashes with AttributeError: 'bool' object has no attribute 'lower' after saving with save_as_session in 0.47.2

### ISSUE THREAD

**Issue by smaga38** [kovidgoyal/kitty#10124]
## Describe the bug

After saving a session with `save_as_session` in kitty 0.47.2, the resulting session file cannot be reloaded via `startup_session` (or `kitty --session <file>`). The terminal crashes on startup with `AttributeError: 'bool' object has no attribute 'lower'`.

## To Reproduce

1. Configure `startup_session` in `kitty.conf` (or pass a session file via `kitty --session <file>`).
2. Open several tabs, then save the session with the `save_as_session` action. (The oh-my-kitty project maps this to `ctrl+a>s`, but the default action is enough to reproduce.)
3. Quit kitty.
4. Restart kitty. It crashes during tab restore.

Minimal session file (taken from a real save) that reproduces the crash:

```text
new_tab HOME
layout splits
enabled_layouts splits,stack
set_layout_state {"pairs": {"one": 1}, "opts": {"default_axis_is_horizontal": true, "equalize_on_close": false}, "class": "Splits", "all_windows": {"active_group_idx": 0, "active_group_history": [1], "window_groups": [{"id": 1, "window_ids": [1]}]}}
cd /Users/example
launch 'kitty-unserialize-data={"id": 1}'
focus
focus_tab 0
```

The presence of the JSON boolean `false` in `equalize_on_close` inside the `opts` object is what triggers the crash. Removing that key from `opts` (or saving in 0.47.1) makes the same file load cleanly.

## Expected behavior

Kitty should be able to load its own session file written by `save_as_session`.

## Actual behavior / Stack trace

```text
[0,290] Traceback (most recent call last):
  File "lib/python3.14/kitty/main.py", line 619, in main
  File "lib/python3.14/kitty/main.py", line 601, in kitty_main
  File "lib/python3.14/kitty/main.py", line 345, in __call__
  File "lib/python3.14/kitty/main.py", line 316, in _run_app
  File "lib/python3.14/kitty/boss.py", line 1407, in start
  File "lib/python3.14/kitty/boss.py", line 453, in startup_first_child
  File "lib/python3.14/kitty/boss.py", line 492, in add_os_window
  File "lib/python3.14/kitty/tabs.py", line 1208, in __init__
  File "lib/python3.14/kitty/tabs.py", line 76, in wrapper
  File "lib/python3.14/kitty/tabs.py", line 1215, in add_tabs_from_session
  File "lib/python3.14/kitty/tabs.py", line 229, in __init__
  File "lib/python3.14/kitty/tabs.py", line 305, in startup
  File "lib/python3.14/kitty/tabs.py", line 364, in _startup
  File "lib/python3.14/kitty/layout/base.py", line 526, in unserialize
  File "lib/python3.14/kitty/layout/splits.py", line 983, in set_layout_state
  File "lib/python3.14/kitty/layout/splits.py", line 567, in __init__
  File "lib/python3.14/kitty/conf/utils.py", line 88, in to_bool
AttributeError: 'bool' object has no attribute 'lower'
```

## Root cause (analysis)

`SplitsLayoutOpts.__init__` in `kitty/layout/splits.py` calls `to_bool(data.get('equalize_on_close', 'false'))`. The `data` dict is the JSON-parsed layout state, where `equalize_on_close` is a Python `bool` (`True`/`False`). `to_bool` in `kitty/conf/utils.py` is typed for `str` and calls `.lower()` on its argument, which raises `AttributeError` on a `bool`.

The `equalize_on_close` option was introduced by commit 852fc4a ("Add equalize action and equalize_on_close option to Splits layout", 29 May 2026) and shipped in 0.47.2 (changelog entry: "Splits layout: add an equalize action and an equalize_on_close option (#3489)"). Sessions saved before 0.47.2 do not contain this key and are unaffected.

I verified the bug is present on the current `master` branch as well — the line in `kitty/layout/splits.py` is unchanged from 0.47.2 — so a fix is needed on `main`.

## Workaround until fixed

After every `save_as_session`, post-process the file and remove the `equalize_on_close` key from the `opts` object:

```bash
python3 -c '
import re, pathlib
p = pathlib.Path("~/.config/kitty/default.kitty-session").expanduser()
p.write_text(re.sub(r",\s*\"equalize_on_close\"\s*:\s*(true|false)", "", p.read_text()))
'
```

Or pin to kitty 0.47.1, which does not know about `equalize_on_close` and silently ignores the unknown key on load (this works for sessions saved in 0.47.2 too).

## Environment details

```text
kitty 0.47.2 created by Kovid Goyal
macOS (Apple Silicon)

Reproduced with: kitty --session default.kitty-session
Reproduced with: kitty --config NONE --session default.kitty-session  (crash is in the session file format, not in user config)

Loaded config files:
  /Users/user/.config/kitty/kitty.conf
  /Users/user/.config/kitty/sma.local.conf
  /Users/user/.config/kitty/splits.conf
  /Users/user/.config/kitty/Pnevma.conf
  /Users/user/.config/kitty/current-theme.conf
  /Users/user/.config/kitty/open-actions.conf
```

## Additional context

- Reverting to 0.47.1: works.
- Editing out `equalize_on_close` from the saved session: works.
- A search of existing issues for `to_bool` and `set_layout_state` returns no results, so this appears to be unreported as of 0.47.2.
