### ISSUE TITLE
Cannot compile on gcc 8.0.1

### ISSUE THREAD

**Issue by gagbo** [kovidgoyal/kitty#376]
Hello,

while I have no issue when I run `make all CC=clang`, I discovered that using the default compiler I have, which is : 
```
gcc (GCC) 8.0.1 20180222 (Red Hat 8.0.1-0.16)
```

I get errors in the first few files I try to compile (sorry for the french, but hopefully the -W flags and file locations are clear enough). Maybe there are flags to obtain the behaviour of another version of gcc so it compiles. At least I don't seem to get this issue with clang 
```make
python3 setup.py 
CC: gcc (8,)
Compiling kitty/state.c ...
Compiling kitty/shaders.c ...
Compiling kitty/screen.c ...
Compiling kitty/line.c ...
gcc -MMD -Wextra -Wno-missing-field-initializers -Wall -std=c99 -D_XOPEN_SOURCE=700 -pedantic-errors -Werror -O3 -DNDEBUG -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidden -fPIC -flto -pthread -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=8 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/python3.6m -I/usr/include/python3.6m -c /home/gagbo/soft/kitty/kitty/line.c -o /home/gagbo/soft/kitty/build/fast_data_types-line.c.o
In file included from /home/gagbo/soft/kitty/kitty/line.c:8:
/home/gagbo/soft/kitty/kitty/line.c: Dans la fonction « left_shift »:
/home/gagbo/soft/kitty/kitty/data-types.h:212:5: error: la macro s'étend en des instructions multiples [-Werror=multistatement-macros]
     for(index_type __i__ = (at); __i__ < (line)->xnum - (num); __i__++) { \
     ^~~
/home/gagbo/soft/kitty/kitty/line.c:479:18: note: dans l'expansion de la macro « left_shift_line »
     if (num > 0) left_shift_line(self, at, num);
                  ^~~~~~~~~~~~~~~
/home/gagbo/soft/kitty/kitty/line.c:479:5: note: certaines parties de l'expansion de la macro ne sont pas protégées par cette instruction « if »
     if (num > 0) left_shift_line(self, at, num);
     ^~
In file included from /home/gagbo/soft/kitty/kitty/line.c:8:
/home/gagbo/soft/kitty/kitty/line.c: Au plus haut niveau:
/home/gagbo/soft/kitty/kitty/data-types.h:83:40: error: transtypage entre des types de fonction incompatibles de « PyObject * (*)(Line *) » {alias « struct _object * (*)(struct <anonyme> *) »} vers « PyObject * (*)(PyObject *, PyObject *) » {alias « struct _object * (*)(struct _object *, struct _object *) »} [-Werror=cast-function-type]
 #define METHOD(name, arg_type) {#name, (PyCFunction)name, arg_type, name##_doc},
                                        ^
/home/gagbo/soft/kitty/kitty/line.c:557:5: note: dans l'expansion de la macro « METHOD »
     METHOD(as_ansi, METH_NOARGS)
     ^~~~~~
/home/gagbo/soft/kitty/kitty/data-types.h:83:40: error: transtypage entre des types de fonction incompatibles de « PyObject * (*)(Line *) » {alias « struct _object * (*)(struct <anonyme> *) »} vers « PyObject * (*)(PyObject *, PyObject *) » {alias « struct _object * (*)(struct _object *, struct _object *) »} [-Werror=cast-function-type]
 #define METHOD(name, arg_type) {#name, (PyCFunction)name, arg_type, name##_doc},
                                        ^
/home/gagbo/soft/kitty/kitty/line.c:558:5: note: dans l'expansion de la macro « METHOD »
     METHOD(is_continued, METH_NOARGS)
     ^~~~~~
cc1 : tous les avertissements sont traités comme des erreurs
```

**Comment by kovidgoyal** [comment]
It would help if you built it with

LANG=en_US.UTF-8

otherwise you will have to wait until I get around to installing gcc 8 (kitty compiles fine with gcc 7)

**Comment by kovidgoyal** [comment]
Also, how is it that you have gcc 8 as the default compiler? According to https://gcc.gnu.org/gcc-8/changes.html gcc 8 has not yet been released

**Comment by gagbo** [comment]
Apparently [Fedora](https://fedoraproject.org/wiki/Changes/GCC8) didn't really wait before implementing the change.

Thanks for the LANG tip, I never know which variable to touch for these locale settings

**Comment by kovidgoyal** [comment]
Weird, for something as critical as a compiler, to use an as yet unreleased version...

Anyway, I have made the changes needed to kitty to have it compile with gcc 8.
